<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjc9c5x\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjc9c5x/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQjc9c5x.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQjc9c5x\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQjc9c5x\appDevDebugProjectContainer([
    'container.build_hash' => 'Qjc9c5x',
    'container.build_id' => '5716437f',
    'container.build_time' => 1552977171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjc9c5x');
