<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2an1v2w\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2an1v2w/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2an1v2w.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2an1v2w\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2an1v2w\appDevDebugProjectContainer([
    'container.build_hash' => '2an1v2w',
    'container.build_id' => '7dbf30a7',
    'container.build_time' => 1552552865,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2an1v2w');
